site_name: mini-platform
theme: 
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'CLI':
    - 'Introduction': 'CLI/index.md'
    - 'Creating minictl CLI': 'CLI/creating-minictl/index.md'
    - 'Creating Github repository': 'CLI/creating-github-repository/index.md'
    - 'Building artefact': 'CLI/building-artefact/index.md'
  - 'Continuous Integration':
    - 'Introduction': 'CI/index.md'
    - 'Continuous Integration with Tekton': 'CI/installing-kind/index.md' 
  